cloudprovider: openstack
imageRegistryURL: ""
cloudinit:
  enable: false
  sshPubKeys: []
  bootcmd:
    - sed -i -e '/net.ipv4.conf.*.rp_filter/d' $(grep -ril '\.rp_filter' /etc/sysctl.d/ /usr/lib/sysctl.d/)
    - sysctl -a | grep '\.rp_filter' | awk '{print $1" = 0"}' > /etc/sysctl.d/1000-cilium.conf
    - sysctl --system
  runcmd:
    - sed -i -e '/net.ipv4.conf.*.rp_filter/d' $(grep -ril '\.rp_filter' /etc/sysctl.d/ /usr/lib/sysctl.d/)
    - sysctl -a | grep '\.rp_filter' | awk '{print $1" = 0"}' > /etc/sysctl.d/1000-cilium.conf
    - sysctl --system
openstack:
    authUrl: https://openstack.example.com:5000
    applicationCredentialId: 
    applicationCredentialSecret: 
    availabilityZone: nova
    subnetID: 
    projectId: 
    tenantDomainName: Default
    tenantName: 
    username: 
    domainName: default
    region: RegionOne
    floatingNetID: 
    floatingSubnetID: 
    openstackClientImage: openstacktools/openstack-client
cluster:
  apiAddr: kubernetes.default.svc.cluster.local
  apiPort: 6443
  additionalManifests: {}
  secretsEncryption: false
  upgradeStrategy:
    controlPlaneDrainOptions: 
      enabled: false
      deleteEmptyDirData: false
      disableEviction: false
      gracePeriod: 0
      ignoreErrors: false
      skipWaitForDeleteTimeoutSeconds: 0
      timeout: 0
    workerDrainOptions:
      enabled: false
      deleteEmptyDirData: false
      disableEviction: false
      gracePeriod: 0
      ignoreErrors: false
      skipWaitForDeleteTimeoutSeconds: 0
      timeout: 0
    workerConcurrency: "10%"
    controlPlaneConcurrency: "10%"
  name: placeholder-cluster-name
  kubernetesVersion: v1.21.14+rke2r1
  cni:
    name: cilium
  autoscaler:
    enabled: true
    rancherUrl: https://rancher.placeholder.com
    rancherToken: rancher-token
    image: luizalabscicdmgc/cluster-autoscaler-amd64:dev
monitoring:
  enabled: false
rke:
  rkeIngressChart:
    enabled: true
    replicaCount: "1"
    autoScaling:
      enabled: true
      minReplicas: "1"
      maxReplicas: "3"
  additionalChartValues:
    rke2-cilium:
        cilium:
            mtu: 1430 # can be changed
            hubble:
            metrics:
                enabled:
                - dns:query;ignoreAAAA
                - drop
                - tcp
                - flow
                - icmp
                - http
            relay:
                enabled: true
                image:
                    repository: "cilium/hubble-relay"
                    tag: "v1.12.1"
            ui:
                backend:
                    image:
                        repository: "cilium/hubble-ui-backend"
                        tag: "v0.9.2"
                enabled: true
                frontend:
                    image:
                        repository: "cilium/hubble-ui"
                        tag: "v0.9.2"
                replicas: 1
            image:
                repository: "rancher/mirrored-cilium-cilium"
                tag: "v1.12.1"
            nodeinit:
                image:
                    repository: "rancher/mirrored-cilium-startup-script"
                    tag: "d69851597ea019af980891a4628fb36b7880ec26"
            operator:
                image:
                    repository: "rancher/mirrored-cilium-operator"
                    tag: "v1.12.1"
            preflight:
                image:
                    repository: "rancher/mirrored-cilium-cilium"
                    tag: "v1.12.1"
            kubeProxyReplacement: "strict"
            k8sServiceHost: kubernetes.default.svc.cluster.local
            k8sServicePort: 6443
  rkeIngressRawManifest:
    enabled: false
  etcd:
    args:
      - "quota-backend-bytes=858993459"
      - "max-request-bytes=33554432"
    exposeMetrics: true
    snapshotRetention: 5
    snapshotScheduleCron: "0 */12 * * *" 
  coredns:
    nodelocal:
      enabled: true
  openstackControllerManager:
    image: k8scloudprovider/openstack-cloud-controller-manager
    tag: v1.24.0
    enableLoadBalancerCreateMonitor: false
  cinderCsiPlugin:
    image: k8scloudprovider/cinder-csi-plugin
    tag: v1.25.0
  registries:
    enabled: false
    configs:
      gcr.io:
        authConfigSecretName: secret-example
        caBundle: ''
        insecureSkipVerify: false
    mirrors:
      gcr.io:
        endpoint:
          - 'https://gcr.io'
  nodeScripts: []
  agentEnvVars: []
  kubeapi:
    args: {}
  kubelet:
    args: {}
  localClusterAuthEndpoint: 
    enabled: false
    fqdn: example.rancher.local
    secretName: example-rancher-local-secret
  tlsSan: []
nodepools: []
