{{ if $.Values.cluster.autoscaler.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: rancherconfig
  namespace: {{ $.Release.Namespace }}
  labels:
    managed-by: helm
type: Opaque
stringData:
  secret: |-
    [Global]
    url = {{ $.Values.cluster.autoscaler.rancherUrl | quote }}
    token = {{ $.Values.cluster.autoscaler.rancherToken | quote }}
    rancher_cluster_name = {{ $.Values.cluster.autoscaler.racherClusterName | quote }}
    cluster_name = {{ $.Values.cluster.name | quote }}
{{ end }}